const express = require('express');
const router = express.Router();
router.use('/auth', require('./authRoutes'));
router.use('/users', require('./userRoutes'));
router.use('/farms', require('./farmRoutes'));
router.use('/crops', require('./cropRoutes'));
router.use('/recommendations', require('./recommendationRoutes'));
router.use('/weather', require('./weatherRoutes'));
router.use('/market-prices', require('./marketRoutes'));
router.use('/market', require('./marketRoutes'));
router.use('/pests', require('./pestRoutes'));
router.use('/diseases', require('./diseaseRoutes'));
router.use('/fertilizers', require('./fertilizerRoutes'));
router.use('/guides', require('./guideRoutes'));
router.use('/advisories', require('./advisoryRoutes'));
router.use('/notifications', require('./notificationRoutes'));
router.use('/activities', require('./activityRoutes'));
router.use('/farm-activities', require('./activityRoutes'));
router.use('/planner', require('./activityRoutes'));
router.use('/ai', require('./aiRoutes'));
router.use('/expert', require('./expertRoutes'));
router.use('/admin', require('./adminRoutes'));
router.use('/health', require('./healthRoutes'));
router.use('/upload', require('./uploadRoutes'));
module.exports = router;
