const mongoose = require('mongoose');
const Crop = require('../models/Crop');

const cropsData = [
  {
    name: 'Rice',
    scientificName: 'Oryza sativa',
    localNames: { hi: 'चावल/धान', mr: 'तांदूळ/भात' },
    category: 'cereal',
    suitableSoils: ['alluvial', 'clay', 'loamy'],
    seasons: ['kharif'],
    temperature: { min: 20, max: 35 },
    waterRequirement: 'high',
    durationDays: { min: 120, max: 150 },
    sowingMonths: ['June', 'July'],
    harvestMonths: ['October', 'November'],
    cultivationPractices: 'Rice requires submerged conditions for early growth. Puddling of field is recommended before transplanting. Maintain 2-5 cm water level during vegetative stage.'
  },
  {
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    localNames: { hi: 'गेहूं', mr: 'गहू' },
    category: 'cereal',
    suitableSoils: ['loamy', 'clay', 'alluvial'],
    seasons: ['rabi'],
    temperature: { min: 10, max: 25 },
    waterRequirement: 'moderate',
    durationDays: { min: 120, max: 150 },
    sowingMonths: ['October', 'November'],
    harvestMonths: ['March', 'April'],
    cultivationPractices: 'Wheat needs a well-pulverized seedbed. Pre-sowing irrigation ensures good germination. Critical irrigation stages are crown root initiation, tillering, and flowering.'
  },
  {
    name: 'Maize',
    scientificName: 'Zea mays',
    localNames: { hi: 'मक्का', mr: 'मका' },
    category: 'cereal',
    suitableSoils: ['loamy', 'sandy', 'alluvial'],
    seasons: ['kharif', 'rabi'],
    temperature: { min: 21, max: 30 },
    waterRequirement: 'moderate',
    durationDays: { min: 90, max: 120 },
    sowingMonths: ['June', 'July', 'October'],
    harvestMonths: ['September', 'October', 'February'],
    cultivationPractices: 'Maize is sensitive to waterlogging, requiring good drainage. Ridge and furrow planting is ideal. Weed control is essential during the first 30-45 days.'
  },
  {
    name: 'Jowar',
    scientificName: 'Sorghum bicolor',
    localNames: { hi: 'ज्वार', mr: 'ज्वारी' },
    category: 'cereal',
    suitableSoils: ['black', 'red', 'loamy'],
    seasons: ['kharif', 'rabi'],
    temperature: { min: 25, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 100, max: 120 },
    sowingMonths: ['June', 'July', 'September'],
    harvestMonths: ['October', 'November', 'January'],
    cultivationPractices: 'Highly drought tolerant crop. Deep summer ploughing helps control soil-borne pests. Thinning operations are required 2-3 weeks after sowing to maintain spacing.'
  },
  {
    name: 'Bajra',
    scientificName: 'Pennisetum glaucum',
    localNames: { hi: 'बाजरा', mr: 'बाजरी' },
    category: 'cereal',
    suitableSoils: ['sandy', 'loamy', 'alluvial'],
    seasons: ['kharif'],
    temperature: { min: 25, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 70, max: 90 },
    sowingMonths: ['June', 'July'],
    harvestMonths: ['September', 'October'],
    cultivationPractices: 'Requires minimal water and can grow in marginal soils. Shallow sowing is recommended. Needs protection from birds during grain filling and maturity.'
  },
  {
    name: 'Chickpea',
    scientificName: 'Cicer arietinum',
    localNames: { hi: 'चना', mr: 'हरभरा' },
    category: 'pulse',
    suitableSoils: ['black', 'loamy', 'clay'],
    seasons: ['rabi'],
    temperature: { min: 15, max: 25 },
    waterRequirement: 'low',
    durationDays: { min: 90, max: 120 },
    sowingMonths: ['October', 'November'],
    harvestMonths: ['February', 'March'],
    cultivationPractices: 'Requires deep black cotton soil with good moisture retention. Nipping of apical buds at 30-35 days promotes branching and increases pod count.'
  },
  {
    name: 'Tur',
    scientificName: 'Cajanus cajan',
    localNames: { hi: 'अरहर/तूर', mr: 'तूर' },
    category: 'pulse',
    suitableSoils: ['black', 'red', 'loamy'],
    seasons: ['kharif'],
    temperature: { min: 20, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 150, max: 180 },
    sowingMonths: ['June', 'July'],
    harvestMonths: ['December', 'January'],
    cultivationPractices: 'Deep-rooted drought-hardy legume. Intercropping with soybean, cotton, or bajra is highly recommended in Maharashtra dryland farming.'
  },
  {
    name: 'Moong',
    scientificName: 'Vigna radiata',
    localNames: { hi: 'मूंग', mr: 'मूग' },
    category: 'pulse',
    suitableSoils: ['loamy', 'sandy', 'alluvial'],
    seasons: ['kharif', 'zaid'],
    temperature: { min: 25, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 60, max: 75 },
    sowingMonths: ['June', 'March'],
    harvestMonths: ['August', 'May'],
    cultivationPractices: 'Short-duration catch crop that enriches soil nitrogen. Ideal for crop rotation before rabi wheat or jowar. Treat seeds with Rhizobium culture.'
  },
  {
    name: 'Urad',
    scientificName: 'Vigna mungo',
    localNames: { hi: 'उड़द', mr: 'उडीद' },
    category: 'pulse',
    suitableSoils: ['black', 'loamy', 'clay'],
    seasons: ['kharif'],
    temperature: { min: 25, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 70, max: 85 },
    sowingMonths: ['June', 'July'],
    harvestMonths: ['September', 'October'],
    cultivationPractices: 'Grows best in fertile, well-drained loam or black cotton soil. Sensitive to water stagnation. Harvest promptly when 80% pods turn dark brown.'
  },
  {
    name: 'Soybean',
    scientificName: 'Glycine max',
    localNames: { hi: 'सोयाबीन', mr: 'सोयाबीन' },
    category: 'oilseed',
    suitableSoils: ['black', 'loamy'],
    seasons: ['kharif'],
    temperature: { min: 20, max: 30 },
    waterRequirement: 'moderate',
    durationDays: { min: 90, max: 110 },
    sowingMonths: ['June', 'July'],
    harvestMonths: ['September', 'October'],
    cultivationPractices: 'Major cash crop of Vidarbha and Marathwada. Inoculate with Bradyrhizobium japonicum. Avoid sowing until at least 75-100 mm monsoon rain has occurred.'
  },
  {
    name: 'Groundnut',
    scientificName: 'Arachis hypogaea',
    localNames: { hi: 'मूंगफली', mr: 'भुईमूग' },
    category: 'oilseed',
    suitableSoils: ['sandy', 'loamy', 'red'],
    seasons: ['kharif', 'rabi'],
    temperature: { min: 20, max: 30 },
    waterRequirement: 'low',
    durationDays: { min: 100, max: 130 },
    sowingMonths: ['June', 'July', 'January'],
    harvestMonths: ['October', 'November', 'May'],
    cultivationPractices: 'Requires friable, loose sandy loam for easy peg entry into soil. Apply gypsum at flowering (30-40 days) for shell hardening and oil filling.'
  },
  {
    name: 'Mustard',
    scientificName: 'Brassica juncea',
    localNames: { hi: 'सरसों', mr: 'मोहरी' },
    category: 'oilseed',
    suitableSoils: ['loamy', 'alluvial', 'sandy'],
    seasons: ['rabi'],
    temperature: { min: 10, max: 25 },
    waterRequirement: 'low',
    durationDays: { min: 90, max: 115 },
    sowingMonths: ['October', 'November'],
    harvestMonths: ['February', 'March'],
    cultivationPractices: 'Cool-season oilseed with low water needs. Ensure weed-free nursery or line sowing. Protect from aphid infestation during flowering with neem sprays.'
  },
  {
    name: 'Sunflower',
    scientificName: 'Helianthus annuus',
    localNames: { hi: 'सूरजमुखी', mr: 'सूर्यफूल' },
    category: 'oilseed',
    suitableSoils: ['loamy', 'black', 'alluvial'],
    seasons: ['kharif', 'rabi', 'zaid'],
    temperature: { min: 20, max: 28 },
    waterRequirement: 'moderate',
    durationDays: { min: 80, max: 95 },
    sowingMonths: ['June', 'July', 'October'],
    harvestMonths: ['September', 'October', 'January'],
    cultivationPractices: 'Day-neutral crop suitable for all three seasons in Maharashtra. Bee pollination enhances seed filling; maintain honeybee boxes nearby if feasible.'
  },
  {
    name: 'Sesame',
    scientificName: 'Sesamum indicum',
    localNames: { hi: 'तिल', mr: 'तीळ' },
    category: 'oilseed',
    suitableSoils: ['sandy', 'loamy'],
    seasons: ['kharif', 'summer'],
    temperature: { min: 25, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 80, max: 95 },
    sowingMonths: ['June', 'July', 'February'],
    harvestMonths: ['September', 'October', 'May'],
    cultivationPractices: 'Highly drought-tolerant oilseed. Shallow sowing (2 cm) mixed with sand ensures even distribution of tiny seeds. Harvest when bottom pods turn yellowish.'
  },
  {
    name: 'Safflower',
    scientificName: 'Carthamus tinctorius',
    localNames: { hi: 'कुसुम', mr: 'करडई' },
    category: 'oilseed',
    suitableSoils: ['black', 'clay', 'loamy'],
    seasons: ['rabi'],
    temperature: { min: 15, max: 30 },
    waterRequirement: 'low',
    durationDays: { min: 120, max: 140 },
    sowingMonths: ['September', 'October'],
    harvestMonths: ['February', 'March'],
    cultivationPractices: 'Deep-rooted drought-resistant rabi oilseed of Maharashtra. Ideal in residual soil moisture after early kharif crops. Spiny leaves deter grazing animals.'
  },
  {
    name: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    localNames: { hi: 'कपास', mr: 'कापूस' },
    category: 'fiber',
    suitableSoils: ['black', 'alluvial'],
    seasons: ['kharif'],
    temperature: { min: 21, max: 35 },
    waterRequirement: 'moderate',
    durationDays: { min: 150, max: 180 },
    sowingMonths: ['June', 'July'],
    harvestMonths: ['November', 'December', 'January'],
    cultivationPractices: 'Maharashtra white gold. Thrives in deep black cotton soils (regur). Monitor pink bollworm using pheromone traps. Pick clean cotton in dry morning hours.'
  },
  {
    name: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    localNames: { hi: 'गन्ना', mr: 'ऊस' },
    category: 'cash_crop',
    suitableSoils: ['loamy', 'alluvial', 'black'],
    seasons: ['annual'],
    temperature: { min: 20, max: 35 },
    waterRequirement: 'high',
    durationDays: { min: 330, max: 365 },
    sowingMonths: ['October', 'January', 'July'],
    harvestMonths: ['December', 'January', 'February'],
    cultivationPractices: 'Long-duration cash crop requiring heavy organic manure. Drip irrigation saves 40% water and increases tonnage. Earthing up prevents lodging.'
  },
  {
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    localNames: { hi: 'टमाटर', mr: 'टोमॅटो' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'sandy', 'red'],
    seasons: ['kharif', 'rabi', 'zaid'],
    temperature: { min: 18, max: 28 },
    waterRequirement: 'moderate',
    durationDays: { min: 90, max: 120 },
    sowingMonths: ['June', 'October', 'January'],
    harvestMonths: ['September', 'January', 'April'],
    cultivationPractices: 'Provide staking with bamboo or wire for indeterminate varieties. Mulching reduces fruit rotting and weed competition. Maintain uniform soil moisture.'
  },
  {
    name: 'Onion',
    scientificName: 'Allium cepa',
    localNames: { hi: 'प्याज', mr: 'कांदा' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'alluvial', 'sandy'],
    seasons: ['kharif', 'rabi'],
    temperature: { min: 13, max: 26 },
    waterRequirement: 'moderate',
    durationDays: { min: 120, max: 145 },
    sowingMonths: ['July', 'October'],
    harvestMonths: ['November', 'April'],
    cultivationPractices: 'Maharashtra produces over 30% of India’s onions (Nashik, Ahmednagar, Pune). Stop irrigation 15 days before harvest and cure bulbs in shade before storage.'
  },
  {
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    localNames: { hi: 'आलू', mr: 'बटाटा' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'sandy', 'alluvial'],
    seasons: ['rabi'],
    temperature: { min: 15, max: 24 },
    waterRequirement: 'moderate',
    durationDays: { min: 85, max: 115 },
    sowingMonths: ['October', 'November'],
    harvestMonths: ['January', 'February'],
    cultivationPractices: 'Earthing up at 30 days is mandatory to shield developing tubers from sunlight and greening. Requires cool nights (15-18°C) for optimal tuberization.'
  },
  {
    name: 'Brinjal',
    scientificName: 'Solanum melongena',
    localNames: { hi: 'बैंगन', mr: 'वांगी' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'black', 'silt'],
    seasons: ['kharif', 'rabi'],
    temperature: { min: 20, max: 32 },
    waterRequirement: 'moderate',
    durationDays: { min: 120, max: 150 },
    sowingMonths: ['June', 'October'],
    harvestMonths: ['September', 'January'],
    cultivationPractices: 'Hardy warm-season vegetable. Regular harvesting of tender glossy fruits stimulates continuous flowering. Clip shoots affected by shoot and fruit borer.'
  },
  {
    name: 'Okra',
    scientificName: 'Abelmoschus esculentus',
    localNames: { hi: 'भिंडी', mr: 'भेंडी' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'sandy', 'alluvial'],
    seasons: ['kharif', 'summer'],
    temperature: { min: 22, max: 35 },
    waterRequirement: 'moderate',
    durationDays: { min: 65, max: 85 },
    sowingMonths: ['June', 'February'],
    harvestMonths: ['August', 'April'],
    cultivationPractices: 'Warm-season crop with rapid fruit growth. Harvest every 2-3 days when pods are tender and snap easily. Grow YVMV-resistant varieties like Parbhani Kranti.'
  },
  {
    name: 'Cabbage',
    scientificName: 'Brassica oleracea var. capitata',
    localNames: { hi: 'पत्तागोभी', mr: 'कोबी' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'alluvial', 'clay'],
    seasons: ['rabi'],
    temperature: { min: 15, max: 22 },
    waterRequirement: 'moderate',
    durationDays: { min: 75, max: 100 },
    sowingMonths: ['September', 'October'],
    harvestMonths: ['December', 'January'],
    cultivationPractices: 'Cool-season leafy head crop. Transplant 4-week-old seedlings on ridges. Apply balanced NPK with secondary sulphur. Harvest when heads are firm and compact.'
  },
  {
    name: 'Cauliflower',
    scientificName: 'Brassica oleracea var. botrytis',
    localNames: { hi: 'फूलगोभी', mr: 'फ्लॉवर' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'alluvial'],
    seasons: ['rabi'],
    temperature: { min: 15, max: 22 },
    waterRequirement: 'moderate',
    durationDays: { min: 80, max: 105 },
    sowingMonths: ['September', 'October'],
    harvestMonths: ['December', 'January'],
    cultivationPractices: 'Requires cool weather for curd development. Blanching (covering curds with inner leaves) keeps curds snowy white and protects from sunscald.'
  },
  {
    name: 'Chilli',
    scientificName: 'Capsicum annuum',
    localNames: { hi: 'मिर्च', mr: 'मिरची' },
    category: 'spice',
    suitableSoils: ['loamy', 'black', 'sandy'],
    seasons: ['kharif', 'rabi'],
    temperature: { min: 20, max: 30 },
    waterRequirement: 'moderate',
    durationDays: { min: 120, max: 160 },
    sowingMonths: ['June', 'September'],
    harvestMonths: ['October', 'February'],
    cultivationPractices: 'Requires well-drained soil; sensitive to water stagnation. For dry red chillies, sun-dry mature red pods until moisture drops below 10%.'
  },
  {
    name: 'Garlic',
    scientificName: 'Allium sativum',
    localNames: { hi: 'लहसुन', mr: 'लसूण' },
    category: 'spice',
    suitableSoils: ['loamy', 'alluvial', 'black'],
    seasons: ['rabi'],
    temperature: { min: 12, max: 24 },
    waterRequirement: 'moderate',
    durationDays: { min: 120, max: 140 },
    sowingMonths: ['October', 'November'],
    harvestMonths: ['February', 'March'],
    cultivationPractices: 'Plant bold individual cloves vertically at 10x7.5 cm spacing. Requires cool weather during vegetative growth and dry warm conditions during bulb maturity.'
  },
  {
    name: 'Ginger',
    scientificName: 'Zingiber officinale',
    localNames: { hi: 'अदरक', mr: 'आले' },
    category: 'spice',
    suitableSoils: ['loamy', 'sandy', 'alluvial'],
    seasons: ['kharif'],
    temperature: { min: 20, max: 30 },
    waterRequirement: 'moderate',
    durationDays: { min: 210, max: 240 },
    sowingMonths: ['April', 'May'],
    harvestMonths: ['December', 'January'],
    cultivationPractices: 'Plant rhizomes on raised broad beds with assured drainage. Green leaf mulching immediately after planting conserves moisture and accelerates sprouting.'
  },
  {
    name: 'Turmeric',
    scientificName: 'Curcuma longa',
    localNames: { hi: 'हल्दी', mr: 'हळद' },
    category: 'spice',
    suitableSoils: ['loamy', 'alluvial', 'black'],
    seasons: ['kharif'],
    temperature: { min: 20, max: 32 },
    waterRequirement: 'moderate',
    durationDays: { min: 240, max: 270 },
    sowingMonths: ['May', 'June'],
    harvestMonths: ['January', 'February'],
    cultivationPractices: 'Maharashtra (Sangli, Hingoli, Nanded) is India’s turmeric hub. Plant mother rhizomes on ridges. Boil and sun-dry fingers for 10-15 days for curing.'
  },
  {
    name: 'Coriander',
    scientificName: 'Coriandrum sativum',
    localNames: { hi: 'धनिया', mr: 'कोथिंबीर' },
    category: 'spice',
    suitableSoils: ['loamy', 'black', 'alluvial'],
    seasons: ['rabi', 'kharif'],
    temperature: { min: 15, max: 25 },
    waterRequirement: 'low',
    durationDays: { min: 40, max: 70 },
    sowingMonths: ['June', 'October'],
    harvestMonths: ['July', 'December'],
    cultivationPractices: 'Split the whole round seeds into two halves before sowing to double germination. Harvest young tender greens at 35-45 days, or let mature for seed harvest at 90 days.'
  },
  {
    name: 'Carrot',
    scientificName: 'Daucus carota',
    localNames: { hi: 'गाजर', mr: 'गाजर' },
    category: 'vegetable',
    suitableSoils: ['sandy', 'loamy', 'alluvial'],
    seasons: ['rabi'],
    temperature: { min: 15, max: 22 },
    waterRequirement: 'low',
    durationDays: { min: 75, max: 95 },
    sowingMonths: ['October', 'November'],
    harvestMonths: ['December', 'January'],
    cultivationPractices: 'Deep, stone-free loose sandy loam is essential to prevent root forking. Sow on ridges. Maintain uniform light moisture for crisp, sweet root development.'
  },
  {
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    localNames: { hi: 'खीरा', mr: 'काकडी' },
    category: 'vegetable',
    suitableSoils: ['sandy', 'loamy', 'alluvial'],
    seasons: ['kharif', 'zaid'],
    temperature: { min: 22, max: 32 },
    waterRequirement: 'moderate',
    durationDays: { min: 55, max: 75 },
    sowingMonths: ['June', 'February'],
    harvestMonths: ['August', 'April'],
    cultivationPractices: 'Fast-growing cucurbit vine. Training on trellises improves fruit color, reduces soil contact rotting, and makes picking efficient.'
  },
  {
    name: 'Bottle Gourd',
    scientificName: 'Lagenaria siceraria',
    localNames: { hi: 'लौकी/घिया', mr: 'दुधी भोपळा' },
    category: 'vegetable',
    suitableSoils: ['loamy', 'sandy', 'alluvial'],
    seasons: ['kharif', 'zaid'],
    temperature: { min: 22, max: 35 },
    waterRequirement: 'moderate',
    durationDays: { min: 65, max: 90 },
    sowingMonths: ['June', 'February'],
    harvestMonths: ['August', 'April'],
    cultivationPractices: 'Vigorous climber suited for pandal or trellis system. Hand pollination in the evening increases fruit set. Harvest tender light-green cylindrical fruits.'
  },
  {
    name: 'Mango',
    scientificName: 'Mangifera indica',
    localNames: { hi: 'आम', mr: 'आंबा' },
    category: 'fruit',
    suitableSoils: ['alluvial', 'loamy', 'laterite', 'red'],
    seasons: ['annual'],
    temperature: { min: 22, max: 38 },
    waterRequirement: 'low',
    durationDays: { min: 365, max: 365 },
    sowingMonths: ['July', 'August'],
    harvestMonths: ['April', 'May', 'June'],
    cultivationPractices: 'Konkan Alphonso (Hapus) and Kesar are Maharashtra GI champions. Withhold irrigation during winter to stimulate flower bud differentiation.'
  },
  {
    name: 'Grapes',
    scientificName: 'Vitis vinifera',
    localNames: { hi: 'अंगूर', mr: 'द्राक्ष' },
    category: 'fruit',
    suitableSoils: ['sandy', 'loamy', 'red'],
    seasons: ['annual'],
    temperature: { min: 15, max: 35 },
    waterRequirement: 'moderate',
    durationDays: { min: 365, max: 365 },
    sowingMonths: ['January', 'February'],
    harvestMonths: ['March', 'April'],
    cultivationPractices: 'Nashik is India’s wine and table grape capital. Requires strict bower trellis and dual pruning (back pruning in April, forward pruning in October).'
  },
  {
    name: 'Pomegranate',
    scientificName: 'Punica granatum',
    localNames: { hi: 'अनार', mr: 'डाळिंब' },
    category: 'fruit',
    suitableSoils: ['sandy', 'loamy', 'red'],
    seasons: ['annual'],
    temperature: { min: 25, max: 38 },
    waterRequirement: 'low',
    durationDays: { min: 180, max: 210 },
    sowingMonths: ['July', 'August'],
    harvestMonths: ['January', 'February'],
    cultivationPractices: 'Bhagwa variety of Solapur is renowned worldwide. Bahar treatment (water withholding) regulates fruiting season. Bagging protects against sunscald.'
  },
  {
    name: 'Banana',
    scientificName: 'Musa acuminata',
    localNames: { hi: 'केला', mr: 'केळी' },
    category: 'fruit',
    suitableSoils: ['loamy', 'alluvial', 'clay'],
    seasons: ['annual'],
    temperature: { min: 20, max: 35 },
    waterRequirement: 'high',
    durationDays: { min: 300, max: 365 },
    sowingMonths: ['June', 'July', 'October'],
    harvestMonths: ['May', 'June', 'September'],
    cultivationPractices: 'Jalgaon is Maharashtra’s banana capital. High-density planting with tissue culture Grand Naine (G9) under drip fertigation yields 70-80 t/ha.'
  },
  {
    name: 'Guava',
    scientificName: 'Psidium guajava',
    localNames: { hi: 'अमरूद', mr: 'पेरू' },
    category: 'fruit',
    suitableSoils: ['loamy', 'alluvial', 'clay'],
    seasons: ['annual'],
    temperature: { min: 18, max: 35 },
    waterRequirement: 'low',
    durationDays: { min: 180, max: 210 },
    sowingMonths: ['July', 'August'],
    harvestMonths: ['November', 'December', 'January'],
    cultivationPractices: 'Hardy fruit tree tolerant of drought and salinity. Sardar (L-49) is the predominant commercial variety. Meadow orchard system allows high-density planting.'
  }
];

async function seedCrops() {
  try {
    for (const crop of cropsData) {
      const formattedCrop = {
        name: crop.name,
        scientificName: crop.scientificName,
        localNames: crop.localNames || {},
        category: crop.category,
        suitableSoils: crop.suitableSoils || [],
        suitableSeasons: crop.seasons || [],
        tempRange: crop.temperature || { min: 20, max: 35 },
        waterRequirement: crop.waterRequirement,
        duration: crop.durationDays || { min: 90, max: 120 },
        sowingPeriod: Array.isArray(crop.sowingMonths) ? crop.sowingMonths.join(', ') : '',
        harvestPeriod: Array.isArray(crop.harvestMonths) ? crop.harvestMonths.join(', ') : '',
        cultivationPractices: crop.cultivationPractices,
        isActive: true
      };

      await Crop.findOneAndUpdate(
        { name: crop.name },
        formattedCrop,
        { upsert: true, new: true }
      );
    }
    console.log(`Seeded ${cropsData.length} crops successfully`);
  } catch (error) {
    console.error('Error seeding crops:', error);
    throw error;
  }
}

module.exports = seedCrops;
module.exports.cropsData = cropsData;
